

set_property PACKAGE_PIN AC18 [get_ports {clk}]
set_property IOSTANDARD LVCMOS18 [get_ports {clk}]

set_property PACKAGE_PIN Y13 [get_ports {reset}]
set_property IOSTANDARD LVCMOS15 [get_ports {reset}]

set_property PACKAGE_PIN M22 [get_ports {HS}]
set_property PACKAGE_PIN M21 [get_ports {VS}]
set_property IOSTANDARD LVCMOS33 [get_ports {HS}]
set_property IOSTANDARD LVCMOS33 [get_ports {VS}]
set_property SLEW FAST [get_ports {HS}]
set_property SLEW FAST [get_ports {VS}]

set_property PACKAGE_PIN AA10 [get_ports {mode}]
set_property IOSTANDARD LVCMOS15 [get_ports {mode}]
set_property PACKAGE_PIN AB10 [get_ports {pause}]
set_property IOSTANDARD LVCMOS15 [get_ports {pause}]
set_property PACKAGE_PIN AA13 [get_ports {SW}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW}]

set_property PACKAGE_PIN N18 [get_ports {ps2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps2_clk}]
set_property PULLUP true [get_ports {ps2_clk}]
set_property PACKAGE_PIN M19 [get_ports {ps2_data}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps2_data}]
set_property PULLUP true [get_ports {ps2_data}]

set_property PACKAGE_PIN P21 [get_ports {R[3]}]
set_property PACKAGE_PIN R21 [get_ports {R[2]}]
set_property PACKAGE_PIN N22 [get_ports {R[1]}]
set_property PACKAGE_PIN N21 [get_ports {R[0]}]
set_property PACKAGE_PIN T25 [get_ports {G[3]}]
set_property PACKAGE_PIN T24 [get_ports {G[2]}]
set_property PACKAGE_PIN R23 [get_ports {G[1]}]
set_property PACKAGE_PIN R22 [get_ports {G[0]}]
set_property PACKAGE_PIN T23 [get_ports {B[3]}]
set_property PACKAGE_PIN T22 [get_ports {B[2]}]
set_property PACKAGE_PIN R20 [get_ports {B[1]}]
set_property PACKAGE_PIN T20 [get_ports {B[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]


set_property SLEW FAST [get_ports {R[3]}]
set_property SLEW FAST [get_ports {R[2]}]
set_property SLEW FAST [get_ports {R[1]}]
set_property SLEW FAST [get_ports {R[0]}]
set_property SLEW FAST [get_ports {G[3]}]
set_property SLEW FAST [get_ports {G[2]}]
set_property SLEW FAST [get_ports {G[1]}]
set_property SLEW FAST [get_ports {G[0]}]
set_property SLEW FAST [get_ports {B[3]}]
set_property SLEW FAST [get_ports {B[2]}]
set_property SLEW FAST [get_ports {B[1]}]
set_property SLEW FAST [get_ports {B[0]}]



set_property PACKAGE_PIN V18 [get_ports {btn[0]}]
set_property PACKAGE_PIN V19 [get_ports {btn[1]}]
set_property PACKAGE_PIN V14 [get_ports {btn[2]}]
set_property PACKAGE_PIN W14 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn[0]_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn[1]_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn[2]_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn[3]_IBUF]

set_property PACKAGE_PIN W16 [get_ports {BTN_X}]
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X}]

set_property PACKAGE_PIN M24 [get_ports {SEGLED_CLK}]
set_property PACKAGE_PIN M20 [get_ports {SEGLED_CLR}]
set_property PACKAGE_PIN L24 [get_ports {SEGLED_DO}]
set_property PACKAGE_PIN R18 [get_ports {SEGLED_PEN}]

set_property IOSTANDARD LVCMOS33 [get_ports {SEGLED_CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGLED_CLR}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGLED_DO}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGLED_PEN}]